sudo: required
services:
  - docker

before_install:
  - cd client && docker build -t pelhage/patflix -f Dockerfile.dev .

script:
  - docker run pelhage/patflix npm run test

deploy:
  # Travis can also deploy to DigitalOcean
  provider: elasticbeanstalk
  # PatflixClient-env-1.eba-j92fh94f.us-west-2.elasticbeanstalk.com
  region: "us-west-2"
  app: "Patflix Client"
  env: "PatflixClient-env-1"
  # Travis will copy all files in S3
  bucket_name: "elasticbeanstalk-us-west-2-344335153300"
  bucket_path: "Patflix Client"
  on:
    branch: rewrite
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
